### ISSUE TITLE
Make access to dynamic predicate faster

### ISSUE THREAD

**Issue by pmoura** [PaulBrownMagic/Frames#2]
Access to local dynamic predicates such as:

https://github.com/PaulBrownMagic/Frames/blob/b41d51b37dad4449a6914a3f1f28da47d530cb6c/tests.lgt#L13

is faster if you also add a scope directive:

```text
:- private(test_collection/1).
```

**Comment by pmoura** [comment]
Same for the `facet_/1` predicate in the `frames` object.

**Comment by PaulBrownMagic** [comment]
Resolved
